#define MAX_ID_LENGTH		20
#define MAX_NICKNAME_LENGTH 13
#define MAX_NAME_LENGTH		20
#define MAX_LOGFILENAME_LENGTH 100
#define SERVER_TICK			500
#define	MAX_PROCESSFUNC		100
#define MAX_TEMPPLAYER		50
#define MAX_AREA			100
#define TEMPPLAYER_UPDATE_TICK   2
#define KEEPALIVE_TICK		30
#define MAX_NPCNAME			20
#define ROW_LINE 60
#define COL_LINE 60
#define CELLROW_LINE 6
#define CELLCOL_LINE 6
#define ALL_CELLCOL_LINE (ROW_LINE / CELLROW_LINE)
#define MAX_ACTIVE_AREAS 9
#define MAX_INACTIVE_AREAS 5

#define TILE_SIZE 12


enum eDirection
{
	DIR_LEFTUP	= 0,
	DIR_UP,
	DIR_RIGHTUP,
	DIR_LEFT,
	DIR_CENTER,
	DIR_RIGHT,
	DIR_LEFTDOWN,
	DIR_DOWN,
	DIR_RIGHTDOWN
};
enum eNpcType
{
	NONE_NPC,
	DETECT_NPC,
	NORMAL_NPC,
};